### ISSUE TITLE
上线经常卡死

### ISSUE THREAD

**Issue by chinachuner** [BiYuqi/vue-element-admin#1]
这个框架如果代码有异常页面会直接卡死崩溃，而不知道是什么原因引起的。
如何可以设置能正常在浏览器里显示js异常 而不是直接卡死呢

**Comment by BiYuqi** [comment]
@chinachuner 
麻烦给具体点的demo:
* 有没有升级相关依赖，比如 vue 和 element-ui 的版本
* 变量不存在的问题，是在chrome上测试的吗
* 现有项目模板可有类似(可重现)的现象？

**Comment by BiYuqi** [comment]
@chinachuner 你把根目录的errorLog.js这个先去掉。在main.js，刚排查了下提交记录,我把这个收集错误的暂时去掉，就会正常报错了.

**Comment by chinachuner** [comment]
嗯  去掉后 不会卡死了。
